// All mean densities are recorded in kg/m3

const elements_mass_list = [
    {material: "Actinium", mean_density: 10070},
    {material: "Aluminum", mean_density: 2702},
    {material: "Americum", mean_density: 13670},
    {material: "Antimony", mean_density: 6684},
    {material: "Argon", mean_density: 1.7824},
    {material: "Arsenic", mean_density: 5720},
    {material: "Barium", mean_density: 3590},
    {material: "Berkelium", mean_density: 14780},
    {material: "Beryllium", mean_density: 1848},
    {material: "Bismuth", mean_density: 9750},
    {material: "Boron", mean_density: 2340},
    {material: "Bromine", mean_density: 3119},
    {material: "Cadmium", mean_density: 8650},
    {material: "Calcium", mean_density: 1550},
    {material: "Californium", mean_density: 15100},
    {material: "Carbon", mean_density: 2260},
    {material: "Cerium", mean_density: 6770},
    {material: "Cesium", mean_density: 1873},
    {material: "Chlorine", mean_density: 3.214},
    {material: "Chromium", mean_density: 7190},
    {material: "Cobalt", mean_density: 8900},
    {material: "Copper", mean_density: 8960},
    {material: "Curium", mean_density: 13500},
    {material: "Dysprosium", mean_density: 8550},
    {material: "Erbium", mean_density: 9070},
    {material: "Europium", mean_density: 5240},
    {material: "Fluorine", mean_density: 1.696},
    {material: "Gadolinium", mean_density: 7895},
    {material: "Gallium", mean_density: 5907},
    {material: "Germanium", mean_density: 5323},
    {material: "Gold", mean_density: 19320},
    {material: "Hafnium", mean_density: 13310},
    {material: "Helium", mean_density: 0.1785},
    {material: "Holmium", mean_density: 8800},
    {material: "Hydrogen", mean_density: 0.0899},
    {material: "Indium", mean_density: 7310},
    {material: "Iodine", mean_density: 4930},
    {material: "Iridium", mean_density: 22400},
    {material: "Iron", mean_density: 7874},
    {material: "Krypton", mean_density: 3.75},
    {material: "Lanthanum", mean_density: 6150},
    {material: "Lead", mean_density: 11350},
    {material: "Lithium", mean_density: 534},
    {material: "Lutetium", mean_density: 9840},
    {material: "Magnesium", mean_density: 1738},
    {material: "Manganese", mean_density: 7430},
    {material: "Mercury", mean_density: 13546},
    {material: "Molybdenum", mean_density: 10220},
    {material: "Neodymium", mean_density: 7010},
    {material: "Neon", mean_density: 0.9},
    {material: "Neptunium", mean_density: 20200},
    {material: "Nickel", mean_density: 8900},
    {material: "Niobium", mean_density: 8570},
    {material: "Nitrogen", mean_density: 1.2506},
    {material: "Osmium", mean_density: 22600},
    {material: "Oxygen", mean_density: 1.429},
    {material: "Palladium", mean_density: 12020},
    {material: "Phosphorus", mean_density: 1820},
    {material: "Platinum", mean_density: 21450},
    {material: "Plutonium", mean_density: 19840},
    {material: "Polonium", mean_density: 9300},
    {material: "Potassium", mean_density: 862},
    {material: "Praseodymium", mean_density: 6770},
    {material: "Promethium", mean_density: 7300},
    {material: "Protactinium", mean_density: 15400},
    {material: "Radium", mean_density: 5500},
    {material: "Radon", mean_density: 9.73},
    {material: "Rhenium", mean_density: 21040},
    {material: "Rhodium", mean_density: 12410},
    {material: "Rubidium", mean_density: 1630},
    {material: "Ruthenium", mean_density: 12370},
    {material: "Samarium", mean_density: 7520},
    {material: "Scandium", mean_density: 2990},
    {material: "Selenium", mean_density: 4790},
    {material: "Silicon", mean_density: 2330},
    {material: "Silver", mean_density: 10500},
    {material: "Sodium", mean_density: 971},
    {material: "Strontium", mean_density: 2540},
    {material: "Sulphur", mean_density: 2070},
    {material: "Tantalum", mean_density: 16650},
    {material: "Technetium", mean_density: 11500},
    {material: "Tellurium", mean_density: 6240},
    {material: "Terbium", mean_density: 8230},
    {material: "Thallium", mean_density: 11850},
    {material: "Thorium", mean_density: 11724},
    {material: "Thulium", mean_density: 9320},
    {material: "Tin", mean_density: 7310},
    {material: "Titanium", mean_density: 4540},
    {material: "Tungsten", mean_density: 19350},
    {material: "Uranium", mean_density: 18950},
    {material: "Vanadium", mean_density: 6110},
    {material: "Xenon", mean_density: 5.9},
    {material: "Ytterbium", mean_density: 6900},
    {material: "Yttrium", mean_density: 4470},
    {material: "Zinc", mean_density: 7130},
    {material: "Zirconium", mean_density: 6510},
];

const stainless_steels_mass_list = [
    {material: "301", mean_density: 7870},
    {material: "302", mean_density: 7890},
    {material: "303", mean_density: 7870},
    {material: "304", mean_density: 8000},
    {material: "304L", mean_density: 8000},
    {material: "305", mean_density: 8010},
    {material: "309", mean_density: 7970},
    {material: "310", mean_density: 7990},
    {material: "316", mean_density: 8000},
    {material: "316L", mean_density: 8000},
    {material: "316Ti", mean_density: 8010},
    {material: "317", mean_density: 7940},
    {material: "321", mean_density: 7930},
    {material: "347", mean_density: 7930},
    {material: "904L", mean_density: 7940},
    {material: "254 SMO", mean_density: 7930},
    {material: "AL‑6XN", mean_density: 8000},
    {material: "409", mean_density: 7700},
    {material: "430", mean_density: 7700},
    {material: "434", mean_density: 7750},
    {material: "410", mean_density: 7750},
    {material: "420", mean_density: 7750},
    {material: "440C", mean_density: 7750},
    {material: "2205", mean_density: 7800},
    {material: "2507", mean_density: 7850},
    {material: "S32750", mean_density: 7850},
    {material: "17‑4 PH", mean_density: 7750},
    {material: "15‑5 PH", mean_density: 7750},
    {material: "13‑8 PH", mean_density: 7750},
];

const steels_mass_list = [
    {material: "1008", mean_density: 7872},
    {material: "1018", mean_density: 7870},
    {material: "1045", mean_density: 7870},
    {material: "1095", mean_density: 7850},
    {material: "12L14", mean_density: 7870},
    {material: "4130", mean_density: 7850},
    {material: "4140", mean_density: 7850},
    {material: "8620", mean_density: 7850},
    {material: "52100", mean_density: 7810},
    {material: "A36", mean_density: 7850},
    {material: "SUJ2", mean_density: 7850},
    {material: "A2", mean_density: 7860},
    {material: "D2", mean_density: 7700},
    {material: "M2", mean_density: 8138},
    {material: "H13", mean_density: 7760},
];

const human_mass_list = [
    // https://www.icrp.org/publication.asp?id=ICRP%20Publication%20110 (pages 44-45 and 52-55)
    // https://bionumbers.hms.harvard.edu/files/Density%20and%20mass%20of%20each%20organ-tissue.pdf
    // https://bionumbers.hms.harvard.edu/files/masses%20and%20mass%20densities%20of%20body%20segments.pdf
    {material: "Adipose tissue", mean_density: 919.6},
    {material: "Adrenals", mean_density: 1030},
    {material: "Air inside body", mean_density: 1.293},
    {material: "Anterior nasal passage", mean_density: 1030},
    {material: "Arm lower (forearm)", mean_density: 1130},
    {material: "Arm lower and Hand", mean_density: 1140},
    {material: "Arm upper", mean_density: 1070},
    {material: "Blood", mean_density: 1060},
    {material: "Blood vessels", mean_density: 1060},
    {material: "Bone ", mean_density: 1750},
    {material: "Bone active marrow", mean_density: 1030},
    {material: "Bone cortical", mean_density: 1920},
    {material: "Bone inactive marrow", mean_density: 980},
    {material: "Bone medullary cavity", mean_density: 980},
    {material: "Bone spongiosa (female)", mean_density: 1280},
    {material: "Bone spongiosa (male)", mean_density: 1300},
    {material: "Brain", mean_density: 1050},
    {material: "Breast", mean_density: 976},
    {material: "Breast, adipose tissue", mean_density: 950},
    {material: "Breast, glandular tissue", mean_density: 1020},
    {material: "Bronchi", mean_density: 1030},
    {material: "Cartilage", mean_density: 1100},
    {material: "Cell", mean_density: 1040},
    {material: "Eye ", mean_density: 1050},
    {material: "Eye lenses", mean_density: 1000},
    {material: "Fat", mean_density: 909.4},
    {material: "Foot", mean_density: 1100},
    {material: "Foot and lower leg", mean_density: 1090},
    {material: "Gall bladder", mean_density: 1030},
    {material: "Hand", mean_density: 1160},
    {material: "Head and neck", mean_density: 1110},
    {material: "Heart wall", mean_density: 1050},
    {material: "Kidney", mean_density: 1050},
    {material: "Leg lower (calf)", mean_density: 1090},
    {material: "Leg total", mean_density: 1060},
    {material: "Leg upper (thigh)", mean_density: 1050},
    {material: "Liver", mean_density: 1050},
    {material: "Lungs", mean_density: 410},
    {material: "Lymphatic tissue", mean_density: 1030},
    {material: "Muscle", mean_density: 1050},
    {material: "Oral mucosa", mean_density: 1050},
    {material: "Ovary", mean_density: 1040},
    {material: "Pancreas", mean_density: 1050},
    {material: "Pituitary gland", mean_density: 1030},
    {material: "Posterior nasal passage down to larynx", mean_density: 1030},
    {material: "Prostate", mean_density: 1030},
    {material: "Residual tissue", mean_density: 950},
    {material: "Salivary glands", mean_density: 1030},
    {material: "Skin", mean_density: 1090},
    {material: "Spinal cord", mean_density: 1030},
    {material: "Spleen", mean_density: 1040},
    {material: "Stomach wall", mean_density: 1040},
    {material: "Small intestine wall", mean_density: 1040},
    {material: "Colon wall", mean_density: 1040},
    {material: "Recto-sigmoid colon wall", mean_density: 1040},
    {material: "Teeth", mean_density: 2750},
    {material: "Testis", mean_density: 1040},
    {material: "Thymus", mean_density: 1030},
    {material: "Thyroid", mean_density: 1040},
    {material: "Tongue", mean_density: 1050},
    {material: "Tonsils", mean_density: 1030},
    {material: "Total Arm", mean_density: 1110},
    {material: "Trachea", mean_density: 1030},
    {material: "Trunk", mean_density: 1030},
    {material: "Ureter", mean_density: 1030},
    {material: "Urinary bladder", mean_density: 1040},
    {material: "Uterus/cervix", mean_density: 1030},
];

const wood_mass_list = [
    // https://www.engineeringtoolbox.com/wood-density-d_40.html
    {material: "Alder ", mean_density: 550},
    {material: "Afrormosia ", mean_density: 710},
    {material: "Agba ", mean_density: 510},
    {material: "Apple ", mean_density: 750},
    {material: "Ash, white ", mean_density: 750},
    {material: "Ash, black ", mean_density: 540},
    {material: "Ash, European ", mean_density: 710},
    {material: "Aspen ", mean_density: 420},
    {material: "Balsa ", mean_density: 125},
    {material: "Bamboo ", mean_density: 355},
    {material: "Basswood ", mean_density: 455},
    {material: "Beech ", mean_density: 800},
    {material: "Birch ", mean_density: 640},
    {material: "Birch, British ", mean_density: 670},
    {material: "Birch, European ", mean_density: 670},
    {material: "Blue gum ", mean_density: 1000},
    {material: "Box ", mean_density: 1055},
    {material: "Butternut ", mean_density: 380},
    {material: "Cedar ", mean_density: 530},
    {material: "Cedar of Lebanon ", mean_density: 580},
    {material: "Cedar, western red ", mean_density: 380},
    {material: "Cherry ", mean_density: 765},
    {material: "Cherry, European ", mean_density: 630},
    {material: "Chestnut, sweet ", mean_density: 560},
    {material: "Cottonwood ", mean_density: 410},
    {material: "Cypress ", mean_density: 510},
    {material: "Dogwood ", mean_density: 760},
    {material: "Douglas Fir ", mean_density: 530},
    {material: "Ebony ", mean_density: 1220},
    {material: "Elm ", mean_density: 570},
    {material: "Elm, American ", mean_density: 570},
    {material: "Elm, English ", mean_density: 575},
    {material: "Elm, Dutch ", mean_density: 560},
    {material: "Elm, Wych ", mean_density: 690},
    {material: "Elm, Rock ", mean_density: 820},
    {material: "Gaboon ", mean_density: 430},
    {material: "Greenheart ", mean_density: 1040},
    {material: "Gum, Black ", mean_density: 590},
    {material: "Gum, Blue ", mean_density: 820},
    {material: "Gum, Red ", mean_density: 540},
    {material: "Hackberry ", mean_density: 620},
    {material: "Hemlock, western ", mean_density: 500},
    {material: "Hickory ", mean_density: 765},
    {material: "Holly ", mean_density: 760},
    {material: "Iroko ", mean_density: 660},
    {material: "Juniper ", mean_density: 560},
    {material: "Keruing ", mean_density: 740},
    {material: "Larch ", mean_density: 530},
    {material: "Lignum Vitae ", mean_density: 1250},
    {material: "Lime, European ", mean_density: 560},
    {material: "Locust ", mean_density: 690},
    {material: "Logwood ", mean_density: 910},
    {material: "Madrone ", mean_density: 740},
    {material: "Magnolia ", mean_density: 570},
    {material: "Mahogany, African ", mean_density: 675},
    {material: "Mahogany, Cuban ", mean_density: 660},
    {material: "Mahogany, Honduras ", mean_density: 650},
    {material: "Mahogany, Spanish ", mean_density: 850},
    {material: "Maple ", mean_density: 685},
    {material: "Meranti, dark red ", mean_density: 710},
    {material: "Myrtle ", mean_density: 660},
    {material: "Oak ", mean_density: 750},
    {material: "Oak, American Red ", mean_density: 740},
    {material: "Oak, American White ", mean_density: 770},
    {material: "Oak, English Brown ", mean_density: 740},
    {material: "Obeche ", mean_density: 390},
    {material: "Oregon Pine ", mean_density: 530},
    {material: "Parana Pine ", mean_density: 560},
    {material: "Pear ", mean_density: 670},
    {material: "Pecan ", mean_density: 770},
    {material: "Persimmon ", mean_density: 900},
    {material: "Philippine Red Luan ", mean_density: 590},
    {material: "Pine, pitch ", mean_density: 840},
    {material: "Pine, Corsican ", mean_density: 510},
    {material: "Pine, radiata ", mean_density: 480},
    {material: "Pine, Scots ", mean_density: 510},
    {material: "Pine, white ", mean_density: 425},
    {material: "Pine, yellow ", mean_density: 420},
    {material: "Plane, European ", mean_density: 640},
    {material: "Plum ", mean_density: 720},
    {material: "Poplar ", mean_density: 425},
    {material: "Ramin ", mean_density: 670},
    {material: "Redwood, American ", mean_density: 450},
    {material: "Redwood, European ", mean_density: 510},
    {material: "Rosewood, Bolivian ", mean_density: 820},
    {material: "Rosewood, East Indian ", mean_density: 900},
    {material: "Sapele ", mean_density: 640},
    {material: "Satinwood ", mean_density: 950},
    {material: "Spruce ", mean_density: 630},
    {material: "Spruce, Canadian ", mean_density: 450},
    {material: "Spruce, Norway ", mean_density: 430},
    {material: "Spruce, Sitka ", mean_density: 450},
    {material: "Spruce, western white ", mean_density: 450},
    {material: "Sycamore ", mean_density: 500},
    {material: "Tanguile ", mean_density: 640},
    {material: "Teak, Indian ", mean_density: 820},
    {material: "Teak, African ", mean_density: 980},
    {material: "Teak, Burma ", mean_density: 740},
    {material: "Utile ", mean_density: 660},
    {material: "Walnut ", mean_density: 670},
    {material: "Walnut, Amer Black ", mean_density: 630},
    {material: "Walnut, Claro ", mean_density: 490},
    {material: "Walnut, European ", mean_density: 570},
    {material: "Water gum ", mean_density: 1000},
    {material: "Whitewood, European ", mean_density: 470},
    {material: "Willow ", mean_density: 500},
    {material: "Yew ", mean_density: 670},
    {material: "Zebrawood ", mean_density: 790},
];

const mineral_mass_list = [
    // https://www.engineeringtoolbox.com/mineral-density-d_1555.html (includes some elements which were removed)
    {material: "Acanthite", mean_density: 7250},
    {material: "Acmite", mean_density: 3520},
    {material: "Actinolite", mean_density: 3040},
    {material: "Alabandite", mean_density: 4000},
    {material: "Alamandine", mean_density: 4200},
    {material: "Albite", mean_density: 2620},
    {material: "Allanite", mean_density: 3750},
    {material: "Allemontite", mean_density: 6150},
    {material: "Allophane", mean_density: 1900},
    {material: "Altaite", mean_density: 8140},
    {material: "Alunite", mean_density: 2745},
    {material: "Amblygonite", mean_density: 3045},
    {material: "Analcime", mean_density: 2300},
    {material: "Anatese", mean_density: 3900},
    {material: "Andalusite", mean_density: 3150},
    {material: "Andesine", mean_density: 2670},
    {material: "Andradite", mean_density: 3900},
    {material: "Anglesite", mean_density: 6300},
    {material: "Ankerite", mean_density: 3050},
    {material: "Annebergite", mean_density: 3050},
    {material: "Anorthite", mean_density: 2730},
    {material: "Anorthoclase", mean_density: 2580},
    {material: "Anthophyllite", mean_density: 3210},
    {material: "Anthydrite", mean_density: 2970},
    {material: "Antlerite", mean_density: 3900},
    {material: "Apatite", mean_density: 3190},
    {material: "Apidote", mean_density: 3450},
    {material: "Apophyllite", mean_density: 2340},
    {material: "Aragonite", mean_density: 2930},
    {material: "Arfvedsonite", mean_density: 3440},
    {material: "Argenite", mean_density: 7300},
    {material: "Arsenopyrite", mean_density: 6070},
    {material: "Atacamite", mean_density: 3760},
    {material: "Augite", mean_density: 3400},
    {material: "Aurichalcite", mean_density: 3770},
    {material: "Autonite", mean_density: 3150},
    {material: "Awaruite", mean_density: 8000},
    {material: "Axinite", mean_density: 3280},
    {material: "Azurite", mean_density: 3830},
    {material: "Barite", mean_density: 4480},
    {material: "Bastnaesite", mean_density: 4950},
    {material: "Beidellite", mean_density: 2150},
    {material: "Beryl", mean_density: 2765},
    {material: "Biotite", mean_density: 3150},
    {material: "Bismite", mean_density: 9000},
    {material: "Boehmite", mean_density: 3030},
    {material: "Boracite", mean_density: 2900},
    {material: "Borax", mean_density: 1710},
    {material: "Bornite", mean_density: 5090},
    {material: "Boulangerite", mean_density: 6000},
    {material: "Brannerite", mean_density: 5500},
    {material: "Braunite", mean_density: 4760},
    {material: "Bravoite", mean_density: 5010},
    {material: "Brochantite", mean_density: 3970},
    {material: "Bromargyrite", mean_density: 5900},
    {material: "Bronzite", mean_density: 3550},
    {material: "Brookite", mean_density: 4110},
    {material: "Brucite", mean_density: 2390},
    {material: "Bytownite", mean_density: 2710},
    {material: "Calcite", mean_density: 2710},
    {material: "Calomel", mean_density: 6450},
    {material: "Calvarite", mean_density: 9040},
    {material: "Cancrinite", mean_density: 2450},
    {material: "Carnallite", mean_density: 1600},
    {material: "Carnotite", mean_density: 4200},
    {material: "Cassiterite", mean_density: 6900},
    {material: "Celestite", mean_density: 3950},
    {material: "Celsian", mean_density: 3250},
    {material: "Cerargyrite", mean_density: 5550},
    {material: "Cerussite", mean_density: 6580},
    {material: "Cervanite", mean_density: 6500},
    {material: "Chabazite", mean_density: 2090},
    {material: "Chalcanthite", mean_density: 2210},
    {material: "Chalcocite", mean_density: 5650},
    {material: "Chalcopyrite", mean_density: 4190},
    {material: "Chlorite", mean_density: 2420},
    {material: "Chloritoid", mean_density: 3655},
    {material: "Chondrodite", mean_density: 3150},
    {material: "Chromite", mean_density: 4795},
    {material: "Chrysoberyl", mean_density: 3670},
    {material: "Chrysocolla", mean_density: 2200},
    {material: "Cinnibar", mean_density: 8100},
    {material: "Clinochlore", mean_density: 2650},
    {material: "Clinoclase", mean_density: 4290},
    {material: "Clinoenstatite", mean_density: 3400},
    {material: "Clinoferrosilite", mean_density: 4100},
    {material: "Clinohumite", mean_density: 3260},
    {material: "Clinzoite", mean_density: 3340},
    {material: "Cobaltite", mean_density: 6330},
    {material: "Colemanite", mean_density: 2420},
    {material: "Columbite", mean_density: 6300},
    {material: "Cordierite", mean_density: 2660},
    {material: "Corundum", mean_density: 4050},
    {material: "Coveillite", mean_density: 4680},
    {material: "Cristobalite", mean_density: 2270},
    {material: "Crocoite", mean_density: 6000},
    {material: "Cryolite", mean_density: 2970},
    {material: "Cubanite", mean_density: 4700},
    {material: "Cummingtonite", mean_density: 3350},
    {material: "Cuprite", mean_density: 6100},
    {material: "Danburite", mean_density: 2990},
    {material: "Datolite", mean_density: 2900},
    {material: "Diamond", mean_density: 3510},
    {material: "Diaspore", mean_density: 3400},
    {material: "Dickite", mean_density: 2600},
    {material: "Digenite", mean_density: 5600},
    {material: "Diopside", mean_density: 3400},
    {material: "Dioptase", mean_density: 3310},
    {material: "Dolmite", mean_density: 2840},
    {material: "Dumortierite", mean_density: 3340},
    {material: "Edenite", mean_density: 3020},
    {material: "Embolite", mean_density: 5600},
    {material: "Enargite", mean_density: 4450},
    {material: "Enstatite", mean_density: 3200},
    {material: "Erythrite", mean_density: 3120},
    {material: "Espomite", mean_density: 1670},
    {material: "Euclase", mean_density: 3040},
    {material: "Euxenite", mean_density: 4840},
    {material: "Fayalite", mean_density: 4390},
    {material: "Feberite", mean_density: 7450},
    {material: "Fergusonite", mean_density: 5100},
    {material: "Ferrimolybdite", mean_density: 4250},
    {material: "Ferrosilite", mean_density: 3950},
    {material: "Fluorite", mean_density: 3130},
    {material: "Forsterite", mean_density: 3270},
    {material: "Franklinite", mean_density: 5140},
    {material: "Gadolinite", mean_density: 4250},
    {material: "Gahnite", mean_density: 4300},
    {material: "Galaxite", mean_density: 4230},
    {material: "Galena", mean_density: 7400},
    {material: "Garnierite", mean_density: 2410},
    {material: "Gaylussite", mean_density: 1960},
    {material: "Geocronite", mean_density: 6400},
    {material: "Gersdorffite", mean_density: 6110},
    {material: "Gibbsite", mean_density: 2340},
    {material: "Glauberite", mean_density: 2770},
    {material: "Glauconite", mean_density: 2675},
    {material: "Glaucophane", mean_density: 3070},
    {material: "Gmelinite", mean_density: 2090},
    {material: "Goethite", mean_density: 3800},
    {material: "Goslarite", mean_density: 2000},
    {material: "Graphite", mean_density: 2160},
    {material: "Greenocktite", mean_density: 4490},
    {material: "Grossularite", mean_density: 3570},
    {material: "Gypsum", mean_density: 2300},
    {material: "Halite", mean_density: 2170},
    {material: "Halloysite", mean_density: 2300},
    {material: "Harmotome", mean_density: 2460},
    {material: "Hastingsite", mean_density: 3380},
    {material: "Hausmanite", mean_density: 4760},
    {material: "Hauynite", mean_density: 2450},
    {material: "Hectorite", mean_density: 2500},
    {material: "Hedenbergite", mean_density: 3550},
    {material: "Helvite", mean_density: 3260},
    {material: "Hemimorphite", mean_density: 3450},
    {material: "Hercynite", mean_density: 3950},
    {material: "Hermatite", mean_density: 5300},
    {material: "Hessite", mean_density: 7550},
    {material: "Heulandite", mean_density: 2200},
    {material: "Hornblende", mean_density: 3235},
    {material: "Huebnerite", mean_density: 7150},
    {material: "Humite", mean_density: 3150},
    {material: "Hyalophane", mean_density: 2810},
    {material: "Hydrozincite", mean_density: 3500},
    {material: "Hypersthene", mean_density: 3550},
    {material: "Ice", mean_density: 990},
    {material: "Iddingsite", mean_density: 2650},
    {material: "Idocrase", mean_density: 3400},
    {material: "Illemenite", mean_density: 4720},
    {material: "Illite", mean_density: 2750},
    {material: "Ilvaite", mean_density: 4010},
    {material: "Iodobromite", mean_density: 5700},
    {material: "Iodyrite", mean_density: 5600},
    {material: "Irdosmine", mean_density: 20150},
    {material: "Jacobsite", mean_density: 4750},
    {material: "Jadeite", mean_density: 3300},
    {material: "Jamesonite", mean_density: 5560},
    {material: "Jarosite", mean_density: 3100},
    {material: "Kainite", mean_density: 2100},
    {material: "Kaliophilite", mean_density: 2580},
    {material: "Kaolinite", mean_density: 2600},
    {material: "Kernite", mean_density: 1910},
    {material: "Krennerite", mean_density: 8530},
    {material: "Kyanite", mean_density: 3610},
    {material: "Langbeinite", mean_density: 2830},
    {material: "Larsenite", mean_density: 5900},
    {material: "Laumonite", mean_density: 2290},
    {material: "Lawsonite", mean_density: 3090},
    {material: "Lazulite", mean_density: 3050},
    {material: "Lazurite", mean_density: 2400},
    {material: "Lechatelierite", mean_density: 2575},
    {material: "Lepidocrocite", mean_density: 4000},
    {material: "Lepidolite", mean_density: 2840},
    {material: "Leucite", mean_density: 2470},
    {material: "Liebthenite", mean_density: 3800},
    {material: "Limonite", mean_density: 3650},
    {material: "Linarite", mean_density: 5400},
    {material: "Linneaeite", mean_density: 4800},
    {material: "Lithiophilite", mean_density: 3340},
    {material: "Loellingite", mean_density: 7250},
    {material: "Magnesite", mean_density: 3000},
    {material: "Magnetite", mean_density: 5150},
    {material: "Malachite", mean_density: 3800},
    {material: "Manganite", mean_density: 4340},
    {material: "Manganosite", mean_density: 5180},
    {material: "Marcasite", mean_density: 4890},
    {material: "Margarite", mean_density: 3030},
    {material: "Marialite", mean_density: 2560},
    {material: "Meionite", mean_density: 2690},
    {material: "Melanterite", mean_density: 1890},
    {material: "Melilite", mean_density: 2950},
    {material: "Menaghinite", mean_density: 6380},
    {material: "Miargyrite", mean_density: 5190},
    {material: "Microcline", mean_density: 2560},
    {material: "Microlite", mean_density: 5300},
    {material: "Millerite", mean_density: 5500},
    {material: "Mimetite", mean_density: 7170},
    {material: "Minium", mean_density: 8200},
    {material: "Molybdenite", mean_density: 5500},
    {material: "Monazite", mean_density: 5150},
    {material: "Monticellite", mean_density: 3200},
    {material: "Montmotillonite", mean_density: 2350},
    {material: "Mullite", mean_density: 3050},
    {material: "Musscovite", mean_density: 2820},
    {material: "Nacrite", mean_density: 2600},
    {material: "Nagyagite", mean_density: 7500},
    {material: "Natrolite", mean_density: 2250},
    {material: "Nephheline", mean_density: 2600},
    {material: "Ni skutterudite", mean_density: 6500},
    {material: "Niccolite", mean_density: 7790},
    {material: "Nitre", mean_density: 2100},
    {material: "Nontronite", mean_density: 2300},
    {material: "Norbergite", mean_density: 3150},
    {material: "Noselite", mean_density: 2340},
    {material: "Oligoclase", mean_density: 2650},
    {material: "Opal", mean_density: 2090},
    {material: "Orpiment", mean_density: 3520},
    {material: "Orthoclase", mean_density: 2560},
    {material: "Ottrelite", mean_density: 3520},
    {material: "Paragonite", mean_density: 2780},
    {material: "Pargasite", mean_density: 3120},
    {material: "Pearceite", mean_density: 6130},
    {material: "Pectolite", mean_density: 2860},
    {material: "Pentlandite", mean_density: 4800},
    {material: "Perovskite", mean_density: 4000},
    {material: "Petalite", mean_density: 2420},
    {material: "Petzite", mean_density: 8920},
    {material: "Phenaktite", mean_density: 2980},
    {material: "Phillipsite", mean_density: 2200},
    {material: "Phlogopite", mean_density: 2800},
    {material: "Phosgenite", mean_density: 6150},
    {material: "Phosphuranylite", mean_density: 4100},
    {material: "Pigeonite", mean_density: 3380},
    {material: "Plagionite", mean_density: 5500},
    {material: "Polucite", mean_density: 2900},
    {material: "Polybasite", mean_density: 4800},
    {material: "Polycrase", mean_density: 5000},
    {material: "Polyhalite", mean_density: 2770},
    {material: "Potash alum", mean_density: 1750},
    {material: "Powellite", mean_density: 4340},
    {material: "Prehnite", mean_density: 2870},
    {material: "Proustite", mean_density: 5550},
    {material: "Pyrargyrite", mean_density: 5850},
    {material: "Pyrite", mean_density: 5010},
    {material: "Pyrochlore", mean_density: 5300},
    {material: "Pyrolusite", mean_density: 4730},
    {material: "Pyromorphite", mean_density: 6850},
    {material: "Pyrope", mean_density: 3745},
    {material: "Pyrophyllite", mean_density: 2840},
    {material: "Pyrrhotite", mean_density: 4610},
    {material: "Quartz", mean_density: 2620},
    {material: "Rammelsbergite", mean_density: 7100},
    {material: "Realgar", mean_density: 3560},
    {material: "Rhodochrosite", mean_density: 3690},
    {material: "Rhodonite", mean_density: 3600},
    {material: "Riebeckite", mean_density: 3400},
    {material: "Roscoelite", mean_density: 2970},
    {material: "Rutile", mean_density: 4250},
    {material: "Samarskite", mean_density: 5700},
    {material: "Sanadine", mean_density: 2520},
    {material: "Saponite", mean_density: 2300},
    {material: "Scapolite", mean_density: 2660},
    {material: "Scheelite", mean_density: 6010},
    {material: "Scolecite", mean_density: 2280},
    {material: "Scorodite", mean_density: 3200},
    {material: "Scorzalite", mean_density: 3270},
    {material: "Semseyite", mean_density: 5950},
    {material: "Sepiolite", mean_density: 2000},
    {material: "Serpentine", mean_density: 2590},
    {material: "Siderite", mean_density: 3960},
    {material: "Siegenite", mean_density: 4900},
    {material: "Sillimanite", mean_density: 3240},
    {material: "Sklodowskite", mean_density: 3540},
    {material: "Skutterudite", mean_density: 6500},
    {material: "Smithsonite", mean_density: 4450},
    {material: "Soda nitre", mean_density: 2260},
    {material: "Sodalite", mean_density: 2290},
    {material: "Sperrylite", mean_density: 10580},
    {material: "Spessartine", mean_density: 4180},
    {material: "Sphalerite", mean_density: 4050},
    {material: "Sphene", mean_density: 3480},
    {material: "Spinel group", mean_density: 3645},
    {material: "Spodumene", mean_density: 3150},
    {material: "Stannite", mean_density: 4400},
    {material: "Staurolite", mean_density: 3710},
    {material: "Stephanite", mean_density: 6250},
    {material: "Sternbergite", mean_density: 4220},
    {material: "Stibnite", mean_density: 4630},
    {material: "Stilbite", mean_density: 2150},
    {material: "Stillwellite", mean_density: 4610},
    {material: "Stolzite", mean_density: 8050},
    {material: "Stromeyerite", mean_density: 6150},
    {material: "Strontianite", mean_density: 3780},
    {material: "Sulphur", mean_density: 2060},
    {material: "Sylvanite", mean_density: 8100},
    {material: "Sylvite", mean_density: 1990},
    {material: "Talc", mean_density: 2750},
    {material: "Tantalite", mean_density: 7100},
    {material: "Tennantite", mean_density: 4650},
    {material: "Tenorite", mean_density: 6500},
    {material: "Tephroite", mean_density: 4250},
    {material: "Tetrahedrite", mean_density: 4900},
    {material: "Thenardite", mean_density: 2680},
    {material: "Thomsonite", mean_density: 2340},
    {material: "Thorianite", mean_density: 10000},
    {material: "Thorite", mean_density: 5350},
    {material: "Topaz", mean_density: 3550},
    {material: "Torbernite", mean_density: 3200},
    {material: "Tourmaline", mean_density: 3100},
    {material: "Tremolite", mean_density: 3050},
    {material: "Tridymite", mean_density: 2305},
    {material: "Triphylite", mean_density: 3500},
    {material: "Troilite", mean_density: 4610},
    {material: "Trona", mean_density: 2130},
    {material: "Tungstite", mean_density: 5500},
    {material: "Turquoise", mean_density: 2700},
    {material: "Tyuyamunite", mean_density: 3800},
    {material: "Ulexite", mean_density: 1950},
    {material: "Uraninite", mean_density: 8725},
    {material: "Uranophane", mean_density: 3900},
    {material: "Uvarovite", mean_density: 3600},
    {material: "Vanadinite", mean_density: 6950},
    {material: "Variscite", mean_density: 2500},
    {material: "Vermiculite", mean_density: 2400},
    {material: "Violarite", mean_density: 4650},
    {material: "Vivianite", mean_density: 2650},
    {material: "Wavellite", mean_density: 2340},
    {material: "Willemite", mean_density: 4050},
    {material: "Witherite", mean_density: 4300},
    {material: "Wolframite", mean_density: 7300},
    {material: "Wollastonite", mean_density: 2840},
    {material: "Wulfenite", mean_density: 6750},
    {material: "Wurtzite", mean_density: 4030},
    {material: "Xenotime", mean_density: 4750},
    {material: "Zincite", mean_density: 5565},
    {material: "Zinkenite", mean_density: 5235},
    {material: "Zircon", mean_density: 4650},
    {material: "Zoisite", mean_density: 3300},
];